"""rename refresh_tokens.token to token_hash

Revision ID: 6ff1b6db3214
Revises: a9570e567fb8
Create Date: 2026-07-05 17:23:11.262554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff1b6db3214'
down_revision: Union[str, Sequence[str], None] = 'a9570e567fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', sa.String(length=512), nullable=False))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=512), nullable=False))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=1)
        batch_op.drop_column('token_hash')

    # ### end Alembic commands ###
