"""add users table and reviewer_id FK

Revision ID: 8cf454946710
Revises: d91265378ae2
Create Date: 2026-07-04 22:32:51.712834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf454946710'
down_revision: Union[str, Sequence[str], None] = 'd91265378ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_scores_reviewer_id', 'users', ['reviewer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scores_reviewer_id', type_='foreignkey')

    # ### end Alembic commands ###
