"""add indexes on candidates name, status, role_applied

Revision ID: d91265378ae2
Revises: 95d74130441f
Create Date: 2026-07-04 19:53:53.062852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91265378ae2'
down_revision: Union[str, Sequence[str], None] = '95d74130441f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.create_index(op.f('ix_candidates_role_applied'), 'candidates', ['role_applied'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_role_applied'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_name'), table_name='candidates')
    # ### end Alembic commands ###
