"""unique constraint on refresh_tokens.user_id

Revision ID: daaf59568c8c
Revises: 6ff1b6db3214
Create Date: 2026-07-05 17:56:02.810337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daaf59568c8c'
down_revision: Union[str, Sequence[str], None] = '6ff1b6db3214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_refresh_tokens_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('uq_refresh_tokens_user_id', type_='unique')

    # ### end Alembic commands ###
